### ISSUE TITLE
About Electricity Price Forecast

### ISSUE THREAD

**Issue by MinkaiDavid** [jmyrberg/ProductionScheduling#1]
Hello jmyrberg!

I have a question on the purpose of building price forecast model. Since the unit price of power would be published by power company, and peak-valley electricity price's timeline is also known. Then, why we have to predict it since it could be calculated？

**Comment by jmyrberg** [comment]
Hi! At least in many industrial settings,the electricity is bought from the spot market, where you don't necessarily know the price in advance but you can make a good guess (=forecast). For example, if you had a production plant, you would want to schedule the more energy-intensive production for the cheaper electricity hours, and the less energy-intensive production to more expensive hours.

This of course applies to consumer settings on a smaller scale as well, if you're buying your electricity from the markets instead of having a fixed price contract with your power company. Hope this helps 🙂
